# Generated by Django 5.2.14 on 2026-05-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        ('exercises', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('actual_sets', models.PositiveIntegerField(default=0)),
                ('actual_reps', models.PositiveIntegerField(default=0)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='clients.client')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_logs', to='exercises.exercise')),
                ('plan_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_logs', to='plans.trainingplanexercise')),
                ('trainer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='accounts.traineraccount')),
            ],
            options={
                'ordering': ['-log_date', '-created_at'],
                'indexes': [models.Index(fields=['client', 'exercise', 'log_date'], name='progress_pr_client__d22464_idx')],
            },
        ),
    ]
