# Generated by Django 5.2.14 on 2026-05-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDraftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_length_weeks', models.PositiveIntegerField(default=4)),
                ('session_duration_min', models.PositiveIntegerField(default=45)),
                ('extra_instructions', models.TextField(blank=True)),
                ('trainer_notes', models.TextField(blank=True, help_text="Trainer's edits before accepting")),
                ('draft_json', models.JSONField(blank=True, default=dict)),
                ('raw_summary', models.TextField(blank=True, help_text='Plain-text summary the LLM returned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_drafts', to='plans.trainingplan')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_draft_plans', to='clients.client')),
                ('trainer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_draft_plans', to='accounts.traineraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
