# Generated by Django 5.2.14 on 2026-05-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fitness_goal', models.TextField(blank=True)),
                ('preferred_times', models.CharField(blank=True, help_text="Free-text e.g. 'Mon / Wed / Fri mornings'", max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('trainer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.traineraccount')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['trainer_account', 'status'], name='clients_cli_trainer_16f41f_idx')],
            },
        ),
    ]
