# Generated by Django 5.2.14 on 2026-05-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('upper_body', 'Upper Body'), ('lower_body', 'Lower Body'), ('back', 'Back'), ('core', 'Core'), ('cardio', 'Cardio'), ('mobility', 'Mobility'), ('other', 'Other')], default='other', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('default_sets', models.PositiveIntegerField(default=3)),
                ('default_reps', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='accounts.traineraccount')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('trainer_account', 'name')},
            },
        ),
    ]
