# Generated by Django 5.2.14 on 2026-05-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('training_session', 'Training Session'), ('consultation', 'Consultation'), ('check_in', 'Check-in')], default='training_session', max_length=24)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
                ('trainer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.traineraccount')),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['trainer_account', 'start_at'], name='appointment_trainer_945c33_idx'), models.Index(fields=['client', 'start_at'], name='appointment_client__30b5ab_idx')],
            },
        ),
    ]
