# Generated by Django 5.2.14 on 2026-05-14 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_upgrade_requests', to=settings.AUTH_USER_MODEL)),
                ('trainer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to='accounts.traineraccount')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='subscriptio_status_f14c6a_idx')],
            },
        ),
    ]
